apiVersion: v1
kind: ConfigMap
metadata:
  name: agentfx-config
  namespace: agentfx
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  ARC_TESTNET_RPC_URL: "https://rpc.testnet.arc.network"
  ARC_TESTNET_CHAIN_ID: "5042002"
  AUTO_ESCROW_ADDRESS: "0x1087E71CD83101adF154d8215522EadA51Bf891E"
  USDC_ADDRESS: "0x538d32d3F3eDba7B6fB574972Ea0eF545f0E494a"
